#!/usr/bin/env node
/**
 * Schema validator — validates every data/banks/*.json, data/networks/*.json and
 * data/govt/*.json (+ index.json consistency) against schemas/bank.schema.json,
 * and data/banks/index.json against schemas/index.schema.json (draft 2020-12).
 * Usage: node scripts/validate-schema.js
 * Exit 1 on any failure. Wired into Data CI (schema contract, issue #36).
 */
const fs = require("fs");
const path = require("path");
const Ajv = require("ajv/dist/2020").default;
const addFormats = require("ajv-formats").default;

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

const bankSchema = ajv.compile(JSON.parse(fs.readFileSync(path.join(__dirname, "../schemas/bank.schema.json"), "utf8")));
const indexSchema = ajv.compile(JSON.parse(fs.readFileSync(path.join(__dirname, "../schemas/index.schema.json"), "utf8")));

const DATA_DIR = path.join(__dirname, "../data");

let failures = 0;
let methodCount = 0;

function listEntityFiles(rel) {
  const dir = path.join(DATA_DIR, rel);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith(".json") && f !== "index.json");
}

function validateEntityDir(rel) {
  const files = listEntityFiles(rel);
  let dirMethods = 0;
  files.forEach((f) => {
    const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, rel, f), "utf8"));
    if (!bankSchema(data)) {
      failures++;
      console.error(`FAIL ${rel}/${f}: ${ajv.errorsText(bankSchema.errors)}`);
    } else {
      dirMethods += data.cards.reduce((n, c) => n + c.blocking_methods.length, 0);
    }
  });
  if (failures === 0) {
    console.log(`schema validation: ${rel}/ ${files.length} files OK (${dirMethods} methods)`);
  }
  return { files: files.length, methods: dirMethods };
}

// banks (the primary surface)
const bankFiles = listEntityFiles("banks");
bankFiles.forEach((f) => {
  const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, "banks", f), "utf8"));
  if (!bankSchema(data)) {
    failures++;
    console.error(`FAIL banks/${f}: ${ajv.errorsText(bankSchema.errors)}`);
  } else {
    methodCount += data.cards.reduce((n, c) => n + c.blocking_methods.length, 0);
  }
});
if (failures === 0) {
  console.log(`schema validation: banks/ ${bankFiles.length} files OK`);
}

const banksIndexPath = path.join(DATA_DIR, "banks", "index.json");
if (fs.existsSync(banksIndexPath)) {
  const index = JSON.parse(fs.readFileSync(banksIndexPath, "utf8"));
  if (!indexSchema(index)) {
    failures++;
    console.error(`FAIL banks/index.json: ${ajv.errorsText(indexSchema.errors)}`);
  } else if (index.count !== bankFiles.length) {
    failures++;
    console.error(`FAIL banks/index.json: count ${index.count} != ${bankFiles.length} bank files`);
  }
} else {
  console.error("warn: data/banks/index.json missing");
}

// networks + govt (rail-level entities; same bank schema contract)
const networks = validateEntityDir("networks");
const govt = validateEntityDir("govt");

// networks index consistency (index.json is generated by build-networks.js)
const networksIndexPath = path.join(DATA_DIR, "networks", "index.json");
if (fs.existsSync(networksIndexPath)) {
  const index = JSON.parse(fs.readFileSync(networksIndexPath, "utf8"));
  const expected = [...listEntityFiles("networks"), ...listEntityFiles("govt")];
  const fileSlugs = expected
    .map((f) => {
      const dir = fs.existsSync(path.join(DATA_DIR, "networks", f)) ? "networks" : "govt";
      return JSON.parse(fs.readFileSync(path.join(DATA_DIR, dir, f), "utf8")).slug;
    })
    .sort();
  const indexSlugs = (index.networks || []).map((n) => n.slug).sort();
  if (index.count !== expected.length) {
    failures++;
    console.error(`FAIL networks/index.json: count ${index.count} != ${expected.length} entity files`);
  }
  if (JSON.stringify(fileSlugs) !== JSON.stringify(indexSlugs)) {
    failures++;
    console.error(`FAIL networks/index.json: slugs ${JSON.stringify(indexSlugs)} != files ${JSON.stringify(fileSlugs)}`);
  }
  const indexMethods = (index.networks || []).reduce((n, x) => n + (x.method_count || 0), 0);
  if (index.method_count !== indexMethods) {
    failures++;
    console.error(`FAIL networks/index.json: method_count ${index.method_count} != sum(method_count)=${indexMethods}`);
  }
}

const railFiles = networks.files + govt.files;
const railMethods = networks.methods + govt.methods;
const total = bankFiles.length + railFiles;

if (failures > 0) {
  console.error(`schema validation: ${failures} failed files`);
  process.exit(1);
}
console.log(`schema validation: ${total} entity files + indexes OK (${methodCount + railMethods} methods)`);
